### ISSUE TITLE
Название репозитория

### ISSUE THREAD

**Issue by Sammers21** [Vadya44/-Summer-Practic#4]
Может лучше назвать репозиторий во что-то типо  summer_practice ?

**Comment by Barricade** [comment]
Хуй соси

**Comment by Sammers21** [comment]
@Barricade , пошел нахуй

**Comment by isgulkov** [comment]
Для этого надо создавать новый репозиторий, а тогда сотрутся прекрасные ишью, которые драньков тут публиковал!

**Comment by Sammers21** [comment]
не надо создавать, в найстройках репозитория можно это сделать

**Comment by Vadya44** [comment]
changed ---
